apiVersion: v1
kind: Service
metadata:
  name: proxysql
  labels:
    app: proxysql
    tier: frontend
spec:
  type: NodePort
  ports:
    - nodePort: 30033
      port: 6033
      name: proxysql-mysql
    - nodePort: 30032
      port: 6032
      name: proxysql-admin
  selector:
    app: proxysql
    tier: frontend        
