apiVersion: v1
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables=
    {
            admin_credentials="proxysql-admin:adminpassw0rd"
            mysql_ifaces="0.0.0.0:6032"
            refresh_interval=2000
    }
    mysql_variables=
    {
            threads=4
            max_connections=2048
            default_query_delay=0
            default_query_timeout=36000000
            have_compress=true
            poll_timeout=2000
            interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
            default_schema="information_schema"
            stacksize=1048576
            server_version="5.1.30"
            connect_timeout_server=10000
            monitor_history=60000
            monitor_connect_interval=200000
            monitor_ping_interval=200000
            ping_interval_server_msec=10000
            ping_timeout_server=200
            commands_stats=true
            sessions_sort=true
            monitor_username="proxysql"
            monitor_password="proxysqlpassw0rd"
    }
    mysql_replication_hostgroups =
    (
            { writer_hostgroup=10, reader_hostgroup=20, comment="MySQL Replication 5.7" }
    )
    mysql_servers =
    (
            { address="mysql" , port=3306 , hostgroup=10, max_connections=100 },
    )
    mysql_users =
    (
            { username = "wordpress" , password = "passw0rd" , default_hostgroup = 10 , active = 1 }
    )
    mysql_query_rules =
    (
            {
                    rule_id=100
                    active=1
                    match_pattern="^SELECT .*"
                    destination_hostgroup=10
                    apply=1
            },
            {
                    rule_id=200
                    active=1
                    match_pattern=".*"
                    destination_hostgroup=10
                    apply=1
            }
    )
kind: ConfigMap
metadata:
  creationTimestamp: "2019-07-04T04:45:44Z"
  name: proxysql-configmap-v3
  namespace: default
  resourceVersion: "238071"
  selfLink: /api/v1/namespaces/default/configmaps/proxysql-configmap-v3
  uid: fac3f667-3858-47a7-878f-37dcd7d8a8ad
